### ISSUE TITLE
Match author metadata to other John W. Campbell stories

### ISSUE THREAD

**Issue by robinwhittleton** [bobrk/john-w-campbell_invaders-from-the-infinite#1]
For example:

https://github.com/standardebooks/john-w-campbell_islands-of-space/blob/70786456a746e7a8b2849027ec94f8b22174fa19/src/epub/content.opf#L55-L61

Note that this adds in an `ann` role; the lack of this is causing the m-033 lint error that you’re suppressing. So you can remove this at the same time:

https://github.com/bobrk/john-w-campbell_invaders-from-the-infinite/blob/ad2001b2a0e29c2e7dfa1af859ebfa4cc13642a1/se-lint-ignore.xml#L15-L20

**Comment by bobrk** [comment]
Hmmm, I don't know what the "ann" role is for. Fixed.

**Comment by robinwhittleton** [comment]
`ann` = annotator. Full list at https://www.loc.gov/marc/relators/relaterm.html.

**Comment by bobrk** [comment]
I get that, but I don’t understand how it applies to the author, I guess.
