### ISSUE TITLE
Remove italicisions where they’re phrases that are in MW

### ISSUE THREAD

**Issue by robinwhittleton** [bobrk/john-w-campbell_invaders-from-the-infinite#4]
- `en rapport` (chapter 2)
- `in toto` (chapter 10)
- `in re` (chapter 14)

**Comment by bobrk** [comment]
There was a discussion about this when I hit it before. The rule became, if it is not in the abridged version of m-w, then it should be italicized. If there's something different, I'm happy to comply...

en rapport throws the unabridged banner when found in m-w.

The other two I'll fix.

**Comment by robinwhittleton** [comment]
OK, I was basically waiting for a decision on that thread before I chipped in again 🙂 If we’re going to keep them italicised then that’s fine, but we should add an `xml:lang="fr"`.

**Comment by bobrk** [comment]
Oh, duh, thanks. My brain was throwing French in with Latin. It's not a far throw...
